#include <stdio.h>
#include <windows.h>
#include <time.h>
#include <string.h>

int main() {
  srand(time(NULL));
  FILE *filePTR;
  int i=0,random=rand()%42+1;
  char name[15];
  int b = 0;

  char char1[] = "abcdefghijklmnopqrstuvwxyz"
                 "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

while (1) {
    for (int a = 0; a < 10; a++) {
      name[a] = char1[random];
      random=rand()%61+1;
    }
    name[11]='.';
    name[12]='t';
    name[13]='x';
    name[14]='t';
    filePTR= NULL;
    filePTR = fopen(name,"w");
    fprintf(filePTR, "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n"
    "MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA MUDA\n");
    fclose(filePTR);
    printf("%s\n", name);
    i++;
}
  return 0;
}
